pipeline:
  identifier: Build_HabitBuilder_1689679095510
  name: Build HabitBuilder
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1689679039926
        repoName: ofalvai/HabitBuilder
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: build
                  spec:
                    shell: Sh
                    command: ./gradlew assembleDebug
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
