name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CACHE_DEBUG_ENABLED: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          gradle-home-cache-cleanup: true
          cache-read-only: false
      
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: lintDebug
        
      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-debug.html'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'
        
