name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Debug build
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Unit test
        run: ./gradlew testDebugUnitTest --stacktrace
